# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Vegarden' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Vegarden
	
	workspace 'Vegarden'
  	
  	source 'https://github.com/CocoaPods/Specs.git'

 	pod "LiquidFloatingActionButton"
	pod "KCFloatingActionButton", "~> 2.1.0"
	pod 'AFNetworking', '~> 3.0'
	pod "MagicalRecord"
	#pod 'SwiftString'
	#pod 'FoldingCell' #Problems with swfit 3 not resolved I reckon

	#source 'https://github.com/CocoaPods/Specs.git'
	#platform :ios, '8.0'
	#use_frameworks!

	#pod 'Material', '~> 1.0'

end
