# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.9.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    
  end
################################################################################################
# Run Tests:
  desc "Runs all the tests"
  lane :test do
    scan
  end

################################################################################################
# Take Screenshots automatically for Apsstore:
 desc "Take screenshots"
  lane :screenshot do
    snapshot
  end
  ################################################################################################
  # Create the ipa file for submision:
  desc "Create ipa"
  lane :build do
    increment_build_number
    gym
  end
################################################################################################
# Create code signing and certificate provisioning Profile:
# Note: sigh creates an App Store distribution profile by default. 
# If you want to create an ad hoc profile you would need to specify sigh(adhoc: true). 
# For a development profile it would be sigh(development: true). 
  desc "Creating a code signing certificate and provisioning profile"
  lane :provision do
  
  produce(
      app_name: 'sheinix.Vegarden',
      language: 'English',
      app_version: '1.0',
      sku: 'com.sheinix.Vegarden'
    )
    cert
    sigh(force: true)
  end
 
  error do |lane, exception|
  # This block is called if there was an error running a lane.
  end
################################################################################################
# Testflight :

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
################################################################################################
# Deploy to Appstore:

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end
################################################################################################
  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
